// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pqiclidmixcogskvhxnz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxaWNsaWRtaXhjb2dza3ZoeG56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzNjg0OTUsImV4cCI6MjA1Nzk0NDQ5NX0.0m2SZxv_mp4bHDcWjLL9KczPC0gkp78Rm1ISjPe3ygs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);